const data = {
  products: [
    {
      _id: '1',
      name: 'Men Sport Pant Black',
      category: 'pants',
      image: '/images/p1.jpg',
      price: '55',
      brand: 'Nike',
      rating: '4.5',
      numReviews: 10,
      description: 'durable product',
    },
    {
      _id: '2',
      name: 'Men T-Shirt And Pant',
      category: 'pants',
      image: '/images/p2.jpg',
      price: '35',
      brand: 'Adidas',
      rating: '4.0',
      numReviews: 14,
      description: 'durable product',
    },
    {
      _id: '3',
      name: 'Men Sport Pant Black And Grey',
      category: 'pants',
      image: '/images/p3.jpg',
      price: '60',
      brand: 'Nike',
      rating: '4.7',
      numReviews: 18,
      description: 'durable product',
    },
    {
      _id: '4',
      name: 'Men Sport Pant Grey',
      category: 'pants',
      image: '/images/p4.jpg',
      price: '45',
      brand: 'Puma',
      rating: '4.9',
      numReviews: 11,
      description: 'durable product',
    },
    {
      _id: '5',
      name: 'Three In One T-Shirt',
      category: 't-shirts',
      image: '/images/p5.jpg',
      price: '45',
      brand: 'Lacoste',
      rating: '3.9',
      numReviews: 9,
      description: 'durable product',
    },
    {
      _id: '6',
      name: 'Men Red Shirt',
      category: 'shirts',
      image: '/images/p6.jpg',
      price: '50',
      brand: 'Lacoste',
      rating: '4.4',
      numReviews: 20,
      description: 'durable product',
    },
    {
      _id: '7',
      name: 'Sleeveless Pleated Flare Dress',
      category: 'dress',
      image: '/images/p7.jpg',
      price: '75',
      brand: 'Lacoste',
      rating: '4.0',
      numReviews: 10,
      description: 'durable product',
    },
    {
      _id: '8',
      name: 'Vintage Printed Short-Sleeved Dress',
      category: 'dress',
      image: '/images/p8.jpg',
      price: '77',
      brand: 'Lacoste',
      rating: '3.0',
      numReviews: 9,
      description: 'durable product',
    },
  ],
};

export default data;
